name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure cmake build for testing
      run: cmake -S. -B${{github.workspace}}/test-build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=On
    
    - name: build for testing
      run: cmake --build ${{github.workspace}}/test-build --verbose
      
    - name: test
      run: ctest --test-dir ${{github.workspace}}/test-build
      
    - name: configure cmake for release with debug
      run: cmake -B ${{github.workspace}}/build-release-debug -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: build release with debug symbols
      run: cmake --build ${{github.workspace}}/build-release-debug --verbose
      
    - name: configure cmake for release
      run: cmake -B ${{github.workspace}}/build-release -DCMAKE_BUILD_TYPE=Release
      
    - name: build release
      run: cmake --build ${{github.workspace}}/build-release --verbose
    

